# Site settings
title: Vivek Devulapalli
description: Postdoctoral Researcher at EMPA
theme: minima

# Build settings
markdown: kramdown

# Minima specific settings
minima:
  date_format: "%b %-d, %Y"

# Add navigation items
header_pages:
  - index.md
  - education.md
  - research.md
  - publications.md
  - blog.md
  - contact.md

# Blog settings
permalink: /blog/:year/:month/:day/:title/
show_excerpts: true

# Social links (optional)
minima:
  social_links:
    - platform: github
      user_url: "https://github.com/vivekdevulapalli07"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/vivek-devulapalli-stem/"
    - platform: google_scholar
      user_url: "https://scholar.google.com/citations?user=TE3lrxoAAAAJ&hl=en"